### ISSUE TITLE
Report PDF Cannot Display Chinese characters

### ISSUE THREAD

**Issue by zhangliangnbu** [senaite/senaite.publisher#109]
## Screenshot (optional)
![1621580170(1)](https://user-images.githubusercontent.com/15187878/119102004-28386f00-ba4c-11eb-98af-518776fcf320.png)

As above, the client name are Chinese characters, but not displayed normally. How can I solve this problem? It's very important to me.
Can anyone help me please ?

**Comment by ramonski** [comment]
Hi @zhangliangnbu,
try to change the `font-family` of your report to a font that supports Chinese characters.

**Comment by zhangliangnbu** [comment]
Hi @ramonski , thanks a lot! I have change the `font-family` as below, but it still cannot display Chinese characters.
```html
           <address class="client-address">
              <div class="client-name font-weight-bold">
                <div tal:replace="client/Name|nothing"
                     style="font-family:Lucida Console, Courier, monospace, SimSun;"></div>
              </div>
              <div class="contact-fullname">
                <div tal:replace="contact/Fullname|nothing"
                style="font-family:SimSun;"></div>
              </div>
              <div class="client-street">
                <div tal:replace="client/PostalAddress/address|nothing" 
                style="font-family:Lucida Console, Courier, monospace, SimSun;"></div>
              </div>
```

the `SimSun` is a CSS Chinese font,  and the code is in `senaite.impress/src/senaite/impress/templates/reports/Default.pt` .  
I think what I have done is not right, then  where and how can I  do  to change `font-family` ?

**Comment by ramonski** [comment]
Probably the font `SimSun` is not installed on the Senaite server? All the fonts you would like to use in CSS have to be available on the server.

**Comment by zhangliangnbu** [comment]
@ramonski  Thank you very much 😄 . I have solved this problem by installing a Chinese font on my server.
