### ISSUE TITLE
How to make Logos appear on all pages

### ISSUE THREAD

**Issue by elirabalison** [senaite/senaite.publisher#110]
Is it possible to make a logo or header appear on all pages using senaite.impress? Like the pagination?
Some people suggest me to put the header in inside a tal:repeat but it doesn't work. It will repeat the header in the same page. Can you help please?

**Comment by ramonski** [comment]
Hi @elirabalison,
yes, you need to add the logo in a HTML block with `display: fixed` style set.
Better add such requests here:
https://community.senaite.org/

**Comment by ramonski** [comment]
Correction: `position: fixed`
