### ISSUE TITLE
pyphen==0.11.0 does not support python 2

### ISSUE THREAD

**Issue by JosephSefara** [senaite/senaite.publisher#116]
pyphen==0.11.0 does not support python 2, please use 0.10.0 or less
https://github.com/senaite/senaite.impress/blob/318efe99057ba5ad1c621dbdbf319075c49b5b5c/setup.py#L54

**Comment by ramonski** [comment]
Hmm, you seem to be right what is currently noted on https://pypi.org/project/pyphen/0.11.0.
However, at least for me version `0.11.0` works w/o problems:

```
% ls -lah eggs | grep pyphen
drwxr-xr-x   4 rbartl staff  128 Nov 17 12:35 pyphen-0.11.0-py2.7.egg
```

What error do you get during buildout?

**Comment by JosephSefara** [comment]
I was installing senaite.jsonapi **only** which required other dependencies then I got 
```
ERROR: Could not find a version that satisfies the requirement pyphen==0.11.0 (from senaite.impress==2.1.0->senaite.lims->senaite.core->senaite.jsonapi) (from versions: 0.6, 0.7, 0.8, 0.9, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.9.5, 0.10.0)
ERROR: No matching distribution found for pyphen==0.11.0 (from senaite.impress==2.1.0->senaite.lims->senaite.core->senaite.jsonapi)
```
But I had to put 0.10.0 inside setup.py of senaite.impress for pip to work.

**Comment by ramonski** [comment]
Please ensure you have the `index` URL set in your `buildout.cfg`:

```dosini
[buildout]
index = https://pypi.org/simple/
extends = https://dist.plone.org/release/5.2.7/versions.cfg
find-links =
    https://dist.plone.org/release/5.2.7/
    https://dist.plone.org/thirdparty/
...
```
