### ISSUE TITLE
Render diffrent templates for diffrent clients automatically

### ISSUE THREAD

**Issue by toropok** [senaite/senaite.publisher#120]
We need to generate different sample report templates for different clients.

Is there any built-in mechanism to do so or need to PR this feature?

regards,
--Leo

**Comment by ramonski** [comment]
Hi @toropok,

not sure if I understand that issue right.
Are you talking about the process of creating new report templates through the web or automatically *select* a template based on the client?

The `publish` view accepts request parameters to select the initial `template`, `orientation` and `format`. This can be used to call the publish view with a different setup than configured in the setup.

Nevertheless, better put such requests here:
https://community.senaite.org/ 

Regards, Ramon

**Comment by toropok** [comment]
Hi, @ramonski 

Thanks! Got it. Will post right place next time :)
