### ISSUE TITLE
 PYTHONHTTPSVERIFY=0 buildout failed

### ISSUE THREAD

**Issue by ukarriem** [senaite/senaite.publisher#139]
## Steps to reproduce
 PYTHONHTTPSVERIFY=0 buildout
## Current behavior
Version and requirements information containing beautifulsoup4:
  [versions] constraint on beautifulsoup4: 4.11.1
  Requirement of senaite.impress==2.4.0: beautifulsoup4==4.9.3
  Requirement of zope.testbrowser: BeautifulSoup4
While:
  Installing instance.
Error: The requirement ('beautifulsoup4==4.9.3') is not allowed by your [versions] constraint (4.11.1)
## Expected behavior
complete the build process

**Comment by ramonski** [comment]
Works in recent versions. Please re-open if the error still exists. Thanks!
