### ISSUE TITLE
Remarks field is broken in Senaite LIMS

### ISSUE THREAD

**Issue by Volga163** [senaite/senaite.publisher#99]
## Steps to reproduce
Writing anything in the Remarks field of the analysis in Senaite LIMS.
## Current behavior
Showing the raw data of the output (see the screenshot attached)
## Expected behavior
Showing the text of the remark without anything else e.g. tags or Unicode sequences instead of non-English characters
## Screenshot (optional)
![image](https://user-images.githubusercontent.com/66194925/91498779-0947ea80-e8c9-11ea-8ef3-2ff2433a936c.png)

**Comment by ramonski** [comment]
Fixed in https://github.com/senaite/senaite.impress/pull/103
